# Generated by Django 4.2.20 on 2025-04-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MPAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('user_rating', models.CharField(max_length=10)),
                ('genre', models.ManyToManyField(to='movies.genre')),
                ('mpaa_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.mpaa')),
            ],
        ),
    ]
